services:
  db:
    image: mariadb:latest
    container_name: saek_db
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    env_file:
      - .env

  app:
    build: ./app
    container_name: saek_app
    restart: always
    depends_on:
      - db
    ports:
      - "5411:5411"
    networks:
      - default
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      TZ: ${TZ}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      FRONTEND_DOMAIN: ${FRONTEND_DOMAIN}
      ADMIN_DOMAIN: ${ADMIN_DOMAIN}
    env_file:
      - .env
